### ISSUE TITLE
Masih di online botnya?

### ISSUE THREAD

**Issue by speckwitz** [MoonLGH/bukanbotcs#4]

**Comment by MoonLGH** [comment]
Dikarenakan Discord Membuat Kebijakan Baru tentang "Message Content Access Deprecation for Verified Bots", bot tidak akan menerima message event mulai dari 2022
 [click me](https://support-dev.discord.com/hc/en-us/articles/4404772028055)
 
 dan bot di berhentikan...
 
 
 project bot ini di berhentikan, karena bot ini masih memakai sistem "message command"
 dan sudah ku buat project baru yang rencananya, aku akan memindahkan semua message command dari bot ini menjadi slash command
 [Bot baru](https://github.com/MoonLGH/Tsukari-Bot)
 yang akan di rewrite ulang menggunakan djs 13.1.0, fully slash command, dan Pakai typescript
